"""Add two_factor_secret column to users

Revision ID: 418359801909
Revises: bb670e29e77b
Create Date: 2025-11-03 13:50:04.890689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418359801909'
down_revision = 'bb670e29e77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('two_factor_secret')

    # ### end Alembic commands ###
